### PR TITLE
added test for photometry copier

### PR DESCRIPTION
**Pull request by grg2rsr**
added photometry copier test. Made a base class so multiple tests can share the same code. Took great care to name the class with the longest and most inconvenient name. (=please suggest something better)

### CODE REVIEW

**Comment by grg2rsr** [comment]
:D geil

**Comment by bimac** [comment]
`ruff format` + `ruff check --fix` sollten es richten 😉

**Comment by grg2rsr** [comment]
I am not sure what is going on here. Ruff is not complaining about things I changed.

**Review by bimac — APPROVED** [review]
I fully support long and inconvenient class names.

**Pull request merged**
