### PR TITLE
Videopc

### LINKED ISSUE #570: Generic copy script
For the mesoscope it means I have to change the code in 6 places in order perform a simple copy, with largely redundant code.  Perhaps the following would improve things:

1. The extra stuff that each copy function does can be moved to a Copier method;
2. The Copier class (or its tag) could be passed as a CLI arg so that only one copy function and entry point is required. The Copier class could also be appended to the transfer_me.flag file;
3. We have a generic transfer Copier that simply copies the collections in the experiment description file. It could optionally assert that all files listed in the transfer_me.flag file exist on disk.

Does anyone foresee issues with this? Because we need the copy script up and running as quickly as possible I shall implement a new function for the ScanImage and Timeline computers but would like to refactor this in the future.

### PR DESCRIPTION
**Pull request by bimac**
This fixes #570 and also temporarily adds the single and double camera Bonsai workflows for the mesoscope rig.  These workflows should be consolidated into one parameterized script.

### CODE REVIEW

**Comment by k1o0** [comment]
The generic copy script should be working, however the copy functions (e.g. `transfer_ephys_data`, `transfer_other_data`, etc.) can most likely be consolidated into a single function, with 'tag' as an argument. I'm assuming that we can call these functions from the command line with arguments?

**Review by oliche — CHANGES_REQUESTED** [review]
Several tests rely on the local copy of  settings yaml files.
We should be relying on the template files or on fixtures to make the tests fully portable.

Here is the list of failing tests:

```
test_transfers
    TestIntegrationTransferExperiments
    TestUnitTransferExperiments
        
test_gui
    TestRigWizardModel
``` 

image

**Comment by k1o0** [comment]
This PR also partially resolves #568, #583 and #590

> Several tests rely on the local copy of settings yaml files. We should be relying on the template files or on fixtures to make the tests fully portable.
> 
> Here is the list of failing tests:
> 
> ```
> test_transfers
>     TestIntegrationTransferExperiments
>     TestUnitTransferExperiments
>         
> test_gui
>     TestRigWizardModel
> ```
Agreed! This wasn't related to any changes I made though. In fact I noticed that most iblrig tests fail without a settings yaml

**Review by oliche — COMMENTED** [review]
For some reason `test_gui.TestRigWizardModel ` is still importing settings from the actual settings files and not the rig ones.
We want the tests to not depend on local configurations at all, but this is perhaps more something for @bimac ?

**Pull request merged**
